# Generated by Django 5.1.2 on 2024-10-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeFuncionario', models.CharField(max_length=100)),
                ('dataNascimento', models.DateField()),
                ('eMail', models.EmailField(max_length=254)),
                ('salario', models.FloatField()),
            ],
        ),
    ]
